
window.RDA_DATA = {
bodies:{
subcompact:{name:"Subcompact",cost:300,weight:1000,maxLoad:2300,spaces:7,cargo:0,armorCost:11,armorWeight:5,kind:"sub"},
compact:{name:"Compact",cost:400,weight:1300,maxLoad:3700,spaces:10,cargo:0,armorCost:13,armorWeight:6},
midsize:{name:"Mid-sized",cost:600,weight:1600,maxLoad:4800,spaces:13,cargo:0,armorCost:16,armorWeight:8},
sedan:{name:"Sedan",cost:700,weight:1700,maxLoad:5100,spaces:16,cargo:0,armorCost:18,armorWeight:9},
luxury:{name:"Luxury",cost:800,weight:1800,maxLoad:5500,spaces:19,cargo:0,armorCost:20,armorWeight:10},
wagon:{name:"Station wagon",cost:800,weight:1800,maxLoad:5500,spaces:14,cargo:7,armorCost:20,armorWeight:10},
pickup:{name:"Pickup",cost:900,weight:2100,maxLoad:6500,spaces:13,cargo:11,armorCost:22,armorWeight:11,kind:"pickup"},
camper:{name:"Camper",cost:1400,weight:2300,maxLoad:6500,spaces:17,cargo:7,armorCost:30,armorWeight:14},
van:{name:"Van",cost:1000,weight:2000,maxLoad:6000,spaces:24,cargo:6,armorCost:30,armorWeight:14,kind:"van"}},
chassis:{
light:{name:"Light",loadMod:-.10,costMod:-.20},
standard:{name:"Standard",loadMod:0,costMod:0},
heavy:{name:"Heavy",loadMod:.10,costMod:.50},
extraHeavy:{name:"Extra Heavy",loadMod:.20,costMod:1}},
suspensions:{
light:{name:"Light",costMod:0,hc:1,vanHC:0,subHC:2},
improved:{name:"Improved",costMod:1,hc:2,vanHC:1,subHC:3},
heavy:{name:"Heavy",costMod:1.5,hc:3,vanHC:2,subHC:4},
offroad:{name:"Off-road",costMod:5,hc:2,vanHC:1,subHC:3}},
plants:{
small:{name:"Small",cost:500,weight:500,spaces:3,dp:5,power:800},
medium:{name:"Medium",cost:1000,weight:700,spaces:4,dp:8,power:1400},
large:{name:"Large",cost:2000,weight:900,spaces:5,dp:10,power:2000},
super:{name:"Super",cost:3000,weight:1100,spaces:6,dp:12,power:2600},
sport:{name:"Sport",cost:6000,weight:1000,spaces:6,dp:12,power:3000},
thundercat:{name:"Thundercat",cost:12000,weight:2000,spaces:8,dp:15,power:6700}},
tires:{
standard:{name:"Standard",cost:50,weight:30,dp:4},
heavy:{name:"Heavy-Duty",cost:100,weight:40,dp:6},
puncture:{name:"Puncture-Resistant",cost:200,weight:50,dp:9},
solid:{name:"Solid",cost:500,weight:75,dp:12}},
armorTypes:{
plastic:{name:"Plastic",costMod:1,weightMod:1},
fireproof:{name:"Fireproof",costMod:2,weightMod:1},
reflective:{name:"Laser-Reflective",costMod:1.1,weightMod:1.1},
lrfp:{name:"Reflective Fireproof",costMod:2.5,weightMod:1.1},
metal:{name:"Metal",costMod:2.5,weightMod:5}},
weapons:{
ac:{name:"Autocannon",category:"Small-bore projectile",toHit:6,damage:"3d",dp:4,cost:7250,weight:600,spaces:3,ammo:10,burst:true},
mg:{name:"Machine Gun",category:"Small-bore projectile",toHit:7,damage:"1d",dp:3,cost:1500,weight:200,spaces:1,ammo:20,area:true},
rr:{name:"Recoilless Rifle",category:"Small-bore projectile",toHit:7,damage:"2d",dp:4,cost:1850,weight:350,spaces:2,ammo:10,burst:true},
vmg:{name:"Vulcan Machine Gun",category:"Small-bore projectile",toHit:6,damage:"2d",dp:3,cost:2700,weight:450,spaces:2,ammo:20,area:true},
atg:{name:"Anti-Tank Gun",category:"Large-bore projectile",toHit:8,damage:"3d",dp:5,cost:2500,weight:700,spaces:3,ammo:10,burst:true,volatile:true},
gl:{name:"Grenade Launcher",category:"Large-bore projectile",toHit:7,damage:"grenade",dp:2,cost:1300,weight:240,spaces:2,ammo:10,grenadeLauncher:true},
sg:{name:"Spike Gun",category:"Large-bore projectile",toHit:7,damage:"1d",dp:2,cost:1150,weight:250,spaces:2,ammo:10,area:true,spikeGun:true},
hr:{name:"Heavy Rocket",category:"Rocket",toHit:9,damage:"3d",dp:2,cost:200,weight:100,spaces:1,ammo:1,burst:true,volatile:true},
ltr:{name:"Light Rocket",category:"Rocket",toHit:9,damage:"1d",dp:1,cost:75,weight:25,spaces:.5,ammo:1,burst:true,volatile:true},
mr:{name:"Medium Rocket",category:"Rocket",toHit:9,damage:"2d",dp:2,cost:140,weight:50,spaces:1,ammo:1,burst:true,volatile:true},
mml:{name:"Micromissile Launcher",category:"Rocket",toHit:8,damage:"1d",dp:2,cost:950,weight:125,spaces:1,ammo:10,burst:true,volatile:true},
mnr:{name:"Mini Rocket",category:"Rocket",toHit:9,damage:"1d-1",dp:1,cost:50,weight:20,spaces:1/3,ammo:1,burst:true,volatile:true},
mfr:{name:"Multi-Fire Rocket Pod",category:"Rocket",toHit:9,damage:"1d",dp:3,cost:450,weight:150,spaces:2,ammo:1,projectiles:6,burst:true,volatile:true},
rl:{name:"Rocket Launcher",category:"Rocket",toHit:8,damage:"2d",dp:2,cost:1350,weight:250,spaces:2,ammo:10,burst:true,volatile:true},
ll:{name:"Light Laser",category:"Laser",toHit:6,damage:"1d",dp:2,cost:3000,weight:200,spaces:1,ammo:null,area:true,laser:true,powerDrain:1,fireModifier:0,burnDuration:0},
ml:{name:"Medium Laser",category:"Laser",toHit:6,damage:"2d",dp:2,cost:5500,weight:350,spaces:2,ammo:null,area:true,laser:true,powerDrain:2,fireModifier:1,burnDuration:0},
laser:{name:"Laser",category:"Laser",toHit:6,damage:"3d",dp:2,cost:8000,weight:500,spaces:2,ammo:null,area:true,laser:true,powerDrain:2,fireModifier:1,burnDuration:0},
hl:{name:"Heavy Laser",category:"Laser",toHit:6,damage:"4d",dp:2,cost:12000,weight:1000,spaces:3,ammo:null,area:true,laser:true,powerDrain:3,fireModifier:2,burnDuration:0},
irll:{name:"Infrared Light Laser",category:"Laser",toHit:6,damage:"1d",dp:2,cost:6000,weight:200,spaces:1,ammo:null,area:true,laser:true,infrared:true,powerDrain:1,fireModifier:0,burnDuration:0},
irml:{name:"Infrared Medium Laser",category:"Laser",toHit:6,damage:"2d",dp:2,cost:11000,weight:350,spaces:2,ammo:null,area:true,laser:true,infrared:true,powerDrain:2,fireModifier:1,burnDuration:0},
irlaser:{name:"Infrared Laser",category:"Laser",toHit:6,damage:"3d",dp:2,cost:16000,weight:500,spaces:2,ammo:null,area:true,laser:true,infrared:true,powerDrain:2,fireModifier:1,burnDuration:0},
irhl:{name:"Infrared Heavy Laser",category:"Laser",toHit:6,damage:"4d",dp:2,cost:24000,weight:1000,spaces:3,ammo:null,area:true,laser:true,infrared:true,powerDrain:3,fireModifier:2,burnDuration:0},
ft:{name:"Flamethrower",category:"Flamethrower",toHit:6,damage:"1d",dp:2,cost:750,weight:500,spaces:2,ammo:10,area:true,maxRange:10,fireModifier:4,burnDuration:3,createsSmoke:true,volatile:true},
ps:{name:"Paint Spray",category:"Dropped gas",toHit:null,damage:"paint",dp:2,cost:650,weight:75,spaces:1,ammo:25,dropped:true,cloud:"paint",mountRule:"rearSide"},
ss:{name:"Smokescreen",category:"Dropped gas",toHit:null,damage:"smoke",dp:4,cost:350,weight:75,spaces:1,ammo:10,dropped:true,cloud:"smoke",mountRule:"rearSide"},
foj:{name:"Flaming Oil Jet",category:"Dropped liquid",toHit:null,damage:"1d-2",dp:3,cost:1175,weight:80,spaces:2,ammo:25,dropped:true,hazard:"flamingOil",fireModifier:3,burnDuration:2,volatile:true},
oj:{name:"Oil Jet",category:"Dropped liquid",toHit:null,damage:"hazard",dp:3,cost:500,weight:75,spaces:2,ammo:25,dropped:true,hazard:"oil"},
md:{name:"Minedropper",category:"Dropped solid",toHit:null,damage:"2d",dp:2,cost:1000,weight:200,spaces:2,ammo:10,dropped:true,hazard:"mine",burst:true},
smd:{name:"Spear 1000 Minedropper",category:"Dropped solid",toHit:null,damage:"2d+3",dp:2,cost:1250,weight:200,spaces:2,ammo:5,dropped:true,hazard:"spearMine"},
sd:{name:"Spikedropper",category:"Dropped solid",toHit:null,damage:"1d",dp:4,cost:300,weight:75,spaces:1,ammo:10,dropped:true,hazard:"spikes"}},
grenades:{
concussion:{name:"Concussion",cost:40,effect:"crewStun"},
explosive:{name:"Explosive",cost:25,damage:"1d",effect:"blast"},
fake:{name:"Fake",cost:5,effect:"none"},
flamingOil:{name:"Flaming Oil",cost:75,effect:"flamingOil"},
flash:{name:"Flash",cost:150,effect:"flash"},
flechette:{name:"Flechette",cost:20,effect:"pedestrianOnly"},
foam:{name:"Foam",cost:30,effect:"foam"},
paint:{name:"Paint",cost:20,effect:"paint"},
smoke:{name:"Smoke",cost:20,effect:"smoke"},
tearGas:{name:"Tear Gas",cost:30,effect:"smoke"},
thermite:{name:"Thermite",cost:100,damage:"1d",effect:"blast",fireModifier:2,burnDuration:1},
whitePhosphorus:{name:"White Phosphorus",cost:75,damage:"1d",vehicleHalf:true,effect:"whitePhosphorus",fireModifier:2,burnDuration:1}},
mounts:["front","back","left","right","top","under"]};
